/* ESTUCTURA BD */
CREATE TABLE POKEDEX(
	NUM_POKEDEX INT PRIMARY KEY,
	NOM_POKEMON VARCHAR(100) NOT NULL,
	NIVEL_EVO INT,
	TIPO1 ENUM('NORMAL','FUEGO','AGUA','PLANTA','ELECTRICO','HIELO','LUCHA','VENENO','TIERRA','VOLADOR','PSIQUICO','BICHO','ROCA','FANTASMA','DRAGON') NOT NULL,
	TIPO2 ENUM('NORMAL','FUEGO','AGUA','PLANTA','ELECTRICO','HIELO','LUCHA','VENENO','TIERRA','VOLADOR','PSIQUICO','BICHO','ROCA','FANTASMA','DRAGON'),
	VITALIDAD INT NOT NULL,
	ATAQUE INT NOT NULL,
	AT_ESPECIAL INT NOT NULL,
	DEFENSA INT NOT NULL,
	DEF_ESPECIAL INT NOT NULL,
	VELOCIDAD INT NOT NULL
);

CREATE TABLE POKEMON(
	ID_POKEMON INT PRIMARY KEY AUTO_INCREMENT,
	ID_ENTRENADOR INT,
	ID_RIVAL INT,
	NUM_POKEDEX INT,
	MOTE VARCHAR(20),
	VITALIDAD_MAX INT NOT NULL,
	VITALIDAD_ACT INT NOT NULL,
	ATAQUE INT NOT NULL,
	AT_ESPECIAL INT NOT NULL,
	DEFENSA INT NOT NULL,
	DEF_ESPECIAL INT NOT NULL,
	VELOCIDAD INT NOT NULL,
	NIVEL INT NOT NULL,
	FERTILIDAD INT DEFAULT 5,
	SEXO ENUM('H','M','X'),
	ESTADO ENUM('PARALIZADO','QUEMADO','ENVENENADO','GRAVEMENTE ENVENENADO','DORMIDO','CONGELADO','HELADO','SOMNOLIENTO','POKERUS','DEBILITADO','CONFUSO','ENAMORADO','ATRAPADO','MALDITO','DRENADORAS','CANTO MORTAL','CENTRO DE ATENCION','AMEDRENTADO', 'SIN_ESTADO'),
	EQUIPO INT,
	TIPO_PROPIETARIO ENUM('ENTRENADOR', 'RIVAL'),
	EXPERIENCIA INT
);

CREATE TABLE MOVIMIENTO(
	ID_MOVIMIENTO INT NOT NULL PRIMARY KEY,
	NOM_MOVIMIENTO VARCHAR(20) NOT NULL,
	NIVEL_APRENDIZAJE INT NOT NULL,
	PP_MAX INT,
	TIPO VARCHAR(20),
	POTENCIA INT,
	TIPO_MOV ENUM('NORMAL','FUEGO','AGUA','PLANTA','ELECTRICO','HIELO','LUCHA','VENENO','TIERRA','VOLADOR','PSIQUICO','BICHO','ROCA','FANTASMA','DRAGON'),
	ESTADO VARCHAR(20),
	TURNOS INT,
	MEJORA VARCHAR(20),
	PROBABILIDAD INT
);

CREATE TABLE MOVIMIENTO_POKEMON(
    ID_POKEMON INT,
    ID_MOVIMIENTO INT,
    PP_ACTUALES INT
);

CREATE TABLE ENTRENADOR(
	ID_ENTRENADOR INT PRIMARY KEY,
	USUARIO VARCHAR(100) NOT NULL UNIQUE,
	PASS VARCHAR(20) NOT NULL,
	POKEDOLARES INT DEFAULT 1000,
	RIVALES_VENCIDOS INT
);

CREATE TABLE RIVAL(
	ID_RIVAL INT PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL UNIQUE,
	FRASE_VICTORIA VARCHAR(200),
	FRASE_DERROTA VARCHAR(200),
	FRASE_RENDICION VARCHAR(200)
);

CREATE TABLE OBJETO(
	ID_OBJETO INT PRIMARY KEY,
	NOM_OBJETO VARCHAR(20),
	ATAQUE FLOAT,
	AT_ESPECIAL FLOAT,
	DEFENSA FLOAT,
	DEF_ESPECIAL FLOAT,
	VELOCIDAD FLOAT,
	PRECIO INT
);

CREATE TABLE MOCHILA(
	ID_ENTRENADOR INT,
	ID_OBJETO INT,
	CANTIDAD INT NOT NULL,
	FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID_ENTRENADOR),
	FOREIGN KEY (ID_OBJETO) REFERENCES OBJETO(ID_OBJETO)
);
 
ALTER TABLE MOVIMIENTO_POKEMON
ADD CONSTRAINT MOV_POK_PK PRIMARY KEY (ID_POKEMON, ID_MOVIMIENTO);
 
ALTER TABLE MOVIMIENTO_POKEMON
ADD FOREIGN KEY (ID_POKEMON) REFERENCES POKEMON (ID_POKEMON);
 
ALTER TABLE MOVIMIENTO_POKEMON
ADD FOREIGN KEY (ID_MOVIMIENTO) REFERENCES MOVIMIENTO (ID_MOVIMIENTO);

ALTER TABLE POKEMON
ADD CONSTRAINT PKM_ID_RIV_FK FOREIGN KEY (ID_RIVAL) REFERENCES RIVAL (ID_RIVAL);

ALTER TABLE MOCHILA
ADD CONSTRAINT MOC_PK PRIMARY KEY (ID_ENTRENADOR, ID_OBJETO);

ALTER TABLE POKEMON
ADD CONSTRAINT PKM_ID_ENT_FK FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR (ID_ENTRENADOR);

ALTER TABLE POKEMON
ADD CONSTRAINT PKM_NUM_PKX_FK FOREIGN KEY (NUM_POKEDEX) REFERENCES POKEDEX (NUM_POKEDEX);

ALTER TABLE POKEMON
ADD CONSTRAINT PKM_ID_RIVAL_FK FOREIGN KEY (ID_RIVAL) REFERENCES RIVAL (ID_RIVAL);

ALTER TABLE movimiento_pokemon
DROP FOREIGN KEY movimiento_pokemon_ibfk_1;
 
ALTER TABLE movimiento_pokemon
ADD CONSTRAINT movimiento_pokemon_ibfk_1
FOREIGN KEY (ID_POKEMON) REFERENCES pokemon(ID_POKEMON)
ON DELETE CASCADE;
 
ALTER TABLE POKEMON ADD ID_OBJETO INT REFERENCES OBJETO(ID_OBJETO);

ALTER TABLE OBJETO
ADD EQUIPABLE BOOLEAN DEFAULT FALSE;

UPDATE OBJETO
SET EQUIPABLE = TRUE
WHERE ID_OBJETO IN (1, 2, 3, 4, 5, 6, 7);


/* INSERTS TABLA POKEDEX */
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (1, 'bulbasaur', 16, 'planta', 'veneno', 45, 49, 49, 65, 65, 45);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (2, 'ivysaur', 32, 'planta', 'veneno', 60, 62, 63, 80, 80, 60);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (3, 'venusaur', 0, 'planta', 'veneno', 80, 82, 83, 100, 100, 80);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (4, 'charmander', 16, 'fuego', null, 39, 52, 43, 60, 50, 65);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (5, 'charmeleon', 36, 'fuego', null, 58, 64, 58, 80, 65, 80);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (6, 'charizard', 0, 'fuego', 'volador', 78, 84, 78, 109, 85, 100);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (7, 'squirtle', 16, 'agua', null, 44, 48, 65, 50, 64, 43);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (8, 'wartortle', 36, 'agua', null, 59, 63, 80, 65, 80, 58);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (9, 'blastoise', 0, 'agua', null, 79, 83, 100, 85, 105, 78);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (10, 'caterpie', 7, 'bicho', null, 45, 30, 35, 20, 20, 45);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (11, 'metapod', 10, 'bicho', null, 50, 20, 55, 25, 25, 30);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (12, 'butterfree', 0, 'bicho', 'volador', 60, 45, 50, 90, 80, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (13, 'weedle', 7, 'bicho', 'veneno', 40, 35, 30, 20, 20, 50);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (14, 'kakuna', 10, 'bicho', 'veneno', 45, 25, 50, 25, 25, 35);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (15, 'beedrill', 0, 'bicho', 'veneno', 65, 90, 40, 45, 80, 75);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (16, 'pidgey', 18, 'normal', 'volador', 40, 45, 40, 35, 35, 56);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (17, 'pidgeotto', 36, 'normal', 'volador', 63, 60, 55, 50, 50, 71);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (18, 'pidgeot', 0, 'normal', 'volador', 83, 80, 75, 70, 70, 101);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (19, 'rattata', 20, 'normal', null, 30, 56, 35, 25, 35, 72);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (20, 'raticate', 0, 'normal', null, 55, 81, 60, 50, 70, 97);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (21, 'spearow', 20, 'normal', 'volador', 40, 60, 30, 31, 31, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (22, 'fearow', 0, 'normal', 'volador', 65, 90, 65, 61, 61, 100);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (23, 'ekans', 22, 'veneno', null, 35, 60, 44, 40, 54, 55);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (24, 'arbok', 0, 'veneno', null, 60, 95, 69, 65, 79, 80);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (25, 'pikachu', -1, 'electrico', null, 35, 55, 40, 50, 50, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (26, 'raichu', 0, 'electrico', null, 60, 90, 55, 90, 80, 110);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (27, 'sandshrew', 22, 'tierra', null, 50, 75, 85, 20, 30, 40);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (28, 'sandslash', 0, 'tierra', null, 75, 100, 110, 45, 55, 65);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (29, 'nidoran-f', 16, 'veneno', null, 55, 47, 52, 40, 40, 41);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (30, 'nidorina', -1, 'veneno', null, 70, 62, 67, 55, 55, 56);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (31, 'nidoqueen', 0, 'veneno', 'tierra', 90, 92, 87, 75, 85, 76);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (32, 'nidoran-m', 16, 'veneno', null, 46, 57, 40, 40, 40, 50);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (33, 'nidorino', -1, 'veneno', null, 61, 72, 57, 55, 55, 65);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (34, 'nidoking', 0, 'veneno', 'tierra', 81, 102, 77, 85, 75, 85);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (35, 'clefairy', -1, 'normal', null, 70, 45, 48, 60, 65, 35);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (36, 'clefable', 0, 'normal', null, 95, 70, 73, 95, 90, 60);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (37, 'vulpix', -1, 'fuego', null, 38, 41, 40, 50, 65, 65);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (38, 'ninetales', 0, 'fuego', null, 73, 76, 75, 81, 100, 100);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (39, 'jigglypuff', -1, 'normal', 'normal', 115, 45, 20, 45, 25, 20);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (40, 'wigglytuff', 0, 'normal', 'normal', 140, 70, 45, 85, 50, 45);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (41, 'zubat', 22, 'veneno', 'volador', 40, 45, 35, 30, 40, 55);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (42, 'golbat', -1, 'veneno', 'volador', 75, 80, 70, 65, 75, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (43, 'oddish', 21, 'planta', 'veneno', 45, 50, 55, 75, 65, 30);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (44, 'gloom', -1, 'planta', 'veneno', 60, 65, 70, 85, 75, 40);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (45, 'vileplume', 0, 'planta', 'veneno', 75, 80, 85, 110, 90, 50);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (46, 'paras', 24, 'bicho', 'planta', 35, 70, 55, 45, 55, 25);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (47, 'parasect', 0, 'bicho', 'planta', 60, 95, 80, 60, 80, 30);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (48, 'venonat', 31, 'bicho', 'veneno', 60, 55, 50, 40, 55, 45);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (49, 'venomoth', 0, 'bicho', 'veneno', 70, 65, 60, 90, 75, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (50, 'diglett', 26, 'tierra', null, 10, 55, 25, 35, 45, 95);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (51, 'dugtrio', 0, 'tierra', null, 35, 100, 50, 50, 70, 120);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (52, 'meowth', 28, 'normal', null, 40, 45, 35, 40, 40, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (53, 'persian', 0, 'normal', null, 65, 70, 60, 65, 65, 115);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (54, 'psyduck', 33, 'agua', null, 50, 52, 48, 65, 50, 55);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (55, 'golduck', 0, 'agua', null, 80, 82, 78, 95, 80, 85);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (56, 'mankey', 28, 'lucha', null, 40, 80, 35, 35, 45, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (57, 'primeape', -1, 'lucha', null, 65, 105, 60, 60, 70, 95);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (58, 'growlithe', -1, 'fuego', null, 55, 70, 45, 70, 50, 60);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (59, 'arcanine', 0, 'fuego', null, 90, 110, 80, 100, 80, 95);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (60, 'poliwag', 25, 'agua', null, 40, 50, 40, 40, 40, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (61, 'poliwhirl', -1, 'agua', null, 65, 65, 65, 50, 50, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (62, 'poliwrath', 0, 'agua', 'lucha', 90, 95, 95, 70, 90, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (63, 'abra', 16, 'psiquico', null, 25, 20, 15, 105, 55, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (64, 'kadabra', -1, 'psiquico', null, 40, 35, 30, 120, 70, 105);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (65, 'alakazam', 0, 'psiquico', null, 55, 50, 45, 135, 95, 120);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (66, 'machop', 28, 'lucha', null, 70, 80, 50, 35, 35, 35);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (67, 'machoke', -1, 'lucha', null, 80, 100, 70, 50, 60, 45);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (68, 'machamp', 0, 'lucha', null, 90, 130, 80, 65, 85, 55);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (69, 'bellsprout', 21, 'planta', 'veneno', 50, 75, 35, 70, 30, 40);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (70, 'weepinbell', -1, 'planta', 'veneno', 65, 90, 50, 85, 45, 55);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (71, 'victreebel', 0, 'planta', 'veneno', 80, 105, 65, 100, 70, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (72, 'tentacool', 30, 'agua', 'veneno', 40, 40, 35, 50, 100, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (73, 'tentacruel', 0, 'agua', 'veneno', 80, 70, 65, 80, 120, 100);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (74, 'geodude', 25, 'roca', 'tierra', 40, 80, 100, 30, 30, 20);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (75, 'graveler', -1, 'roca', 'tierra', 55, 95, 115, 45, 45, 35);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (76, 'golem', 0, 'roca', 'tierra', 80, 120, 130, 55, 65, 45);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (77, 'ponyta', 40, 'fuego', null, 50, 85, 55, 65, 65, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (78, 'rapidash', 0, 'fuego', null, 65, 100, 70, 80, 80, 105);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (79, 'slowpoke', 37, 'agua', 'psiquico', 90, 65, 65, 40, 40, 15);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (80, 'slowbro', 0, 'agua', 'psiquico', 95, 75, 110, 100, 80, 30);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (81, 'magnemite', 30, 'electrico', null, 25, 35, 70, 95, 55, 45);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (82, 'magneton', -1, 'electrico', null, 50, 60, 95, 120, 70, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (83, 'farfetchd', -1, 'normal', 'volador', 52, 90, 55, 58, 62, 60);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (84, 'doduo', 31, 'normal', 'volador', 35, 85, 45, 35, 35, 75);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (85, 'dodrio', 0, 'normal', 'volador', 60, 110, 70, 60, 60, 110);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (86, 'seel', 34, 'agua', null, 65, 45, 55, 45, 70, 45);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (87, 'dewgong', 0, 'agua', 'hielo', 90, 70, 80, 70, 95, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (88, 'grimer', 38, 'veneno', null, 80, 80, 50, 40, 50, 25);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (89, 'muk', 0, 'veneno', null, 105, 105, 75, 65, 100, 50);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (90, 'shellder', -1, 'agua', null, 30, 65, 100, 45, 25, 40);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (91, 'cloyster', 0, 'agua', 'hielo', 50, 95, 180, 85, 45, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (92, 'gastly', 25, 'fantasma', 'veneno', 30, 35, 30, 100, 35, 80);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (93, 'haunter', -1, 'fantasma', 'veneno', 45, 50, 45, 115, 55, 95);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (94, 'gengar', 0, 'fantasma', 'veneno', 60, 65, 60, 130, 75, 110);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (95, 'onix', -1, 'roca', 'tierra', 35, 45, 160, 30, 45, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (96, 'drowzee', 26, 'psiquico', null, 60, 48, 45, 43, 90, 42);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (97, 'hypno', 0, 'psiquico', null, 85, 73, 70, 73, 115, 67);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (98, 'krabby', 28, 'agua', null, 30, 105, 90, 25, 25, 50);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (99, 'kingler', 0, 'agua', null, 55, 130, 115, 50, 50, 75);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (100, 'voltorb', 30, 'electrico', null, 40, 30, 50, 55, 55, 100);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (101, 'electrode', 0, 'electrico', null, 60, 50, 70, 80, 80, 150);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (102, 'exeggcute', -1, 'planta', 'psiquico', 60, 40, 80, 60, 45, 40);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (103, 'exeggutor', 0, 'planta', 'psiquico', 95, 95, 85, 125, 75, 55);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (104, 'cubone', 28, 'tierra', null, 50, 50, 95, 40, 50, 35);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (105, 'marowak', 0, 'tierra', null, 60, 80, 110, 50, 80, 45);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (106, 'hitmonlee', 0, 'lucha', null, 50, 120, 53, 35, 110, 87);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (107, 'hitmonchan', 0, 'lucha', null, 50, 105, 79, 35, 110, 76);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (108, 'lickitung', -1, 'normal', null, 90, 55, 75, 60, 75, 30);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (109, 'koffing', 35, 'veneno', null, 40, 65, 95, 60, 45, 35);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (110, 'weezing', 0, 'veneno', null, 65, 90, 120, 85, 70, 60);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (111, 'rhyhorn', 42, 'tierra', 'roca', 80, 85, 95, 30, 30, 25);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (112, 'rhydon', -1, 'tierra', 'roca', 105, 130, 120, 45, 45, 40);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (113, 'chansey', -1, 'normal', null, 250, 5, 5, 35, 105, 50);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (114, 'tangela', -1, 'planta', null, 65, 55, 115, 100, 40, 60);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (115, 'kangaskhan', 0, 'normal', null, 105, 95, 80, 40, 80, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (116, 'horsea', 32, 'agua', null, 30, 40, 70, 70, 25, 60);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (117, 'seadra', -1, 'agua', null, 55, 65, 95, 95, 45, 85);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (118, 'goldeen', 33, 'agua', null, 45, 67, 60, 35, 50, 63);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (119, 'seaking', 0, 'agua', null, 80, 92, 65, 65, 80, 68);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (120, 'staryu', -1, 'agua', null, 30, 45, 55, 70, 55, 85);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (121, 'starmie', 0, 'agua', 'psiquico', 60, 75, 85, 100, 85, 115);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (122, 'mr-mime', 42, 'psiquico', 'normal', 40, 45, 65, 100, 120, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (123, 'scyther', -1, 'bicho', 'volador', 70, 110, 80, 55, 80, 105);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (124, 'jynx', 0, 'hielo', 'psiquico', 65, 50, 35, 115, 95, 95);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (125, 'electabuzz', -1, 'electrico', null, 65, 83, 57, 95, 85, 105);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (126, 'magmar', -1, 'fuego', null, 65, 95, 57, 100, 85, 93);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (127, 'pinsir', 0, 'bicho', null, 65, 125, 100, 55, 70, 85);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (128, 'tauros', 0, 'normal', null, 75, 100, 95, 40, 70, 110);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (129, 'magikarp', 20, 'agua', null, 20, 10, 55, 15, 20, 80);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (130, 'gyarados', 0, 'agua', 'volador', 95, 125, 79, 60, 100, 81);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (131, 'lapras', 0, 'agua', 'hielo', 130, 85, 80, 85, 95, 60);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (132, 'ditto', 0, 'normal', null, 48, 48, 48, 48, 48, 48);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (133, 'eevee', -1, 'normal', null, 55, 55, 50, 45, 65, 55);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (134, 'vaporeon', 0, 'agua', null, 130, 65, 60, 110, 95, 65);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (135, 'jolteon', 0, 'electrico', null, 65, 65, 60, 110, 95, 130);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (136, 'flareon', 0, 'fuego', null, 65, 130, 60, 95, 110, 65);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (137, 'porygon', -1, 'normal', null, 65, 60, 70, 85, 75, 40);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (138, 'omanyte', 40, 'roca', 'agua', 35, 40, 100, 90, 55, 35);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (139, 'omastar', 0, 'roca', 'agua', 70, 60, 125, 115, 70, 55);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (140, 'kabuto', 40, 'roca', 'agua', 30, 80, 90, 55, 45, 55);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (141, 'kabutops', 0, 'roca', 'agua', 60, 115, 105, 65, 70, 80);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (142, 'aerodactyl', 0, 'roca', 'volador', 80, 105, 65, 60, 75, 130);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (143, 'snorlax', 0, 'normal', null, 160, 110, 65, 65, 110, 30);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (144, 'articuno', 0, 'hielo', 'volador', 90, 85, 100, 95, 125, 85);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (145, 'zapdos', 0, 'electrico', 'volador', 90, 90, 85, 125, 90, 100);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (146, 'moltres', 0, 'fuego', 'volador', 90, 100, 90, 125, 85, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (147, 'dratini', 30, 'dragon', null, 41, 64, 45, 50, 50, 50);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (148, 'dragonair', 55, 'dragon', null, 61, 84, 65, 70, 70, 70);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (149, 'dragonite', 0, 'dragon', 'volador', 91, 134, 95, 100, 100, 80);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (150, 'mewtwo', 0, 'psiquico', null, 106, 110, 90, 154, 90, 130);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (151, 'mew', 0, 'psiquico', null, 100, 100, 100, 100, 100, 100);


INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (152, 'Mewtwo Surfero', 0, 'psiquico', 'agua', 116, 90, 140, 164, 100, 140);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (153, 'Balrog', 0, 'fuego', 'psiquico', 130, 110, 110, 170, 140, 95);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (154, 'Carrinchear', 0, 'normal', 'agua', 60, 63, 63, 58, 58, 74);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (155, 'Xaturnino', 0, 'psiquico', 'volador', 75, 85, 105, 80, 80, 105);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (156, 'dReaper', 0, 'fantasma', 'psiquico', 91, 60, 150, 70, 70, 110);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (157, 'Skullgreyd', 0, 'fantasma', 'dragon', 100, 150, 60, 90, 90, 130);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (158, 'vMon', 0, 'agua', null, 55, 58, 58, 53, 53, 69);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (159, 'warGreymon', 0, 'electrico', 'dragon', 110, 120, 120, 100, 100, 90);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (160, 'Ultimate WarGreymon', 0, 'electrico', 'dragon', 70, 150, 150, 80, 80, 150);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (161, 'piedMon', 0, 'lucha', 'fantasma', 75, 80, 160, 80, 80, 130);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (162, 'Druddigon', 0, 'dragon', 'fantasma', 87, 130, 70, 100, 100, 58);

INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (163, 'bulbapunch', 0, 'LUCHA', null, 45, 49, 49, 65, 65, 45);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (164, 'charmanchacra', 0, 'PSIQUICO', null, 39, 52, 43, 60, 50, 65);
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (165, 'tanckquirtel', 0, 'ROCA', null, 44, 48, 65, 50, 64, 43);

INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, NIVEL_EVO, TIPO1, TIPO2, VITALIDAD, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD) VALUES (166, 'Nintales Alola', 0, 'HIELO', null, 73, 67, 80, 75, 100, 102);


/* INSERTS TABLA MOVIMIENTO */
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (1, 'BURBUJA', 1, 30, 'ESPECIAL', 20, 'AGUA', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (2, 'CASCADA', 35, 15, 'FISICO', 80, 'AGUA', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (3, 'HIDROBOMBA', 42, 5, 'ESPECIAL', 120, 'AGUA', 'SIN_ESTADO', 2, null, 80);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (4, 'MARTILLAZO', 44, 10, 'FISICO', 100, 'AGUA', 'SIN_ESTADO', 1, null, 85);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (5, 'CHUPAVIDAS', 25, 10, 'FISICO', 80, 'BICHO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (6, 'DISPARO_DEMORA', 1, 40, 'MEJORA', 0, 'BICHO', 'SIN_ESTADO', 1, 'BAJAR_VELOCIDAD', 95);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (7, 'DOBLE_ATAQUE', 12, 30, 'FISICO', 30, 'LUCHA', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (8, 'PIN_MISIL', 32, 20, 'FISICO', 14, 'BICHO', 'SIN_ESTADO', 1, null, 85);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (9, 'FURIA_DRAGON', 1, 10, 'ESPECIAL', 40, 'DRAGON', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (10, 'IMPACTRUENO', 5, 30, 'ESPECIAL', 40, 'ELECTRICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (11, 'ONDA_TRUENO', 23, 20, 'ESTADO', 0, 'ELECTRICO', 'PARALIZADO', 1, null, 55);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (12, 'PUNO_TRUENO', 43, 15, 'FISICO', 75, 'ELECTRICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (13, 'RAYO', 26, 10, 'ESPECIAL', 95, 'ELECTRICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (14, 'TRUENO', 41, 10, 'ESPECIAL', 110, 'ELECTRICO', 'SIN_ESTADO', 1, null, 70);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (15, 'LENGUETAZO', 1, 30, 'FISICO', 30, 'FANTASMA', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (16, 'RAYO_CONFUSO', 1, 20, 'ESTADO', 0, 'FANTASMA', 'CONFUSO', 2, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (17, 'TINIEBLAS', 1, 10, 'ESPECIAL', 0, 'FANTASMA', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (18, 'ASCUAS', 1, 25, 'ESTADO', 40, 'FUEGO', 'QUEMADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (19, 'LANZALLAMAS', 46, 15, 'ESPECIAL', 95, 'FUEGO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (20, 'LLAMARADA', 56, 5, 'ESPECIAL', 120, 'FUEGO', 'SIN_ESTADO', 1, null, 85);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO, POTENCIA, TIPO_MOV, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (21, 'PUNO_FUEGO', 41, 15, 'FISICO', 75, 'FUEGO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (22, 'PUNO_HIELO', 34, 15, 'HIELO', 75, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (23, 'NIEBLA', 41, 30, 'HIELO', null, 'ESTADO', 'CONGELADO', 1, null, -1); /* PRECISION -1 SIGNIFICA QUE APLICA A TODOS LOS POKEMON PRESENTES */
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (24, 'RAYO_HIELO', 50, 10, 'HIELO', 95, 'ESPECIAL', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (25, 'VENTISCA', 54, 5, 'HIELO', 120, 'ESPECIAL', 'SIN_ESTADO', 1, null, 90);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (26, 'SUMISION', 50, 25, 'LUCHA', 80, 'FISICO', 'SIN_ESTADO', 1, null, 80);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (27, 'DOBLE_PATADA', 45, 30, 'LUCHA', 60, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (28, 'PATADA_GIRO', 33, 15, 'LUCHA', 60, 'FISICO', 'SIN_ESTADO', 1, null, 85);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (29, 'PATADA_BAJA', 20, 20, 'LUCHA', 50, 'FISICO', 'SIN_ESTADO', 1, null, 90);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (30, 'ABSORBER', 25, 20, 'PLANTA', 20, 'ESPECIAL', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (31, 'DANZA_PETALO', 30, 20, 'PLANTA', 70, 'ESPECIAL', 'SIN_ESTADO', 4, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (32, 'DRENADORAS', 17, 10, 'PLANTA', null, 'MEJORA', 'SIN_ESTADO', 1, 'SUBIR_VIDA', 90);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (33, 'ESPORA', 28, 15, 'PLANTA', null, 'ESTADO', 'DORMIDO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (34, 'AGILIDAD', 46, 30, 'PSIQUICO', null, 'MEJORA', 'SIN_ESTADO', 1, 'SUBIR_VELOCIDAD', 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (35, 'AMNESIA', 42, 20, 'PSIQUICO', null, 'MEJORA', 'SIN_ESTADO', 1, 'SUBIR_ATAQUE_ESP', 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (36, 'BARRERA', 35, 30, 'PSIQUICO', null, 'MEJORA', 'SIN_ESTADO', 1, 'SUBIR_DEFENSA_ESP', 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (37, 'COME_SUENOS', 37, 15, 'PSIQUICO', 100, 'ESPECIAL', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (38, 'AVALANCHA', 31, 10, 'ROCA', 75, 'FISICO', 'SIN_ESTADO', 1, null, 90);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (39, 'LANZARROCAS', 16, 15, 'ROCA', 50, 'FISICO', 'SIN_ESTADO', 1, null, 65);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (40, 'EXCAVAR', 19, 10, 'TIERRA', 100, 'FISICO', 'SIN_ESTADO', 2, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (41, 'FISURA', 50, 5, 'TIERRA', 120, 'FISICO', 'SIN_ESTADO', 2, null, 25);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (42, 'HUESO_PALO', 1, 20, 'TIERRA', 65, 'ESTADO', 'AMEDRENTADO', 1, null, 85);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (43, 'TERREMOTO', 39, 10, 'TIERRA', 100, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (44, 'ACIDO', 20, 30, 'VENENO', 40, 'ESPECIAL', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (45, 'ARMADURA_ACIDA', 33, 20, 'VENENO', null, 'MEJORA', 'SIN_ESTADO', 1, 'SUBIR_DEFENSA', 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (46, 'GAS_VENENOSO', 25, 40, 'VENENO', null, 'ESTADO', 'ENVENENADO', 1, null, 90);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (47, 'PICOTAZO_VENENOSO', 14, 35, 'VENENO', 35, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (48, 'ATAQUE_AEREO', 50, 5, 'VOLADOR', 140, 'FISICO', 'SIN_ESTADO', 1, null, 90);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (49, 'ATAQUE_ALA', 22, 35, 'VOLADOR', 60, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (50, 'PLACAJE', 33, 35, 'NORMAL', 40, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (51, 'PICO_TALADRO', 48, 5, 'VOLADOR', 100, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (52, 'PICOTAZO', 10, 35, 'VOLADOR', 35, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (53, 'VUELO', 36, 15, 'VOLADOR', 90, 'FISICO', 'SIN_ESTADO', 2, null, 95);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (54, 'ARANAZO', 5, 35, 'NORMAL', 40, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (55, 'AUTODESTRUCCION', 50, 5, 'NORMAL', 200, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (56, 'CORTE', 10, 30, 'NORMAL', 50, 'FISICO', 'SIN_ESTADO', 1, null, 95);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (57, 'GOLPES_FURIA', 14, 15, 'NORMAL', 18, 'FISICO', 'SIN_ESTADO', 1, null, 85);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (58, 'ATAQUE_FURIA', 28, 20, 'NORMAL', 20, 'FISICO', 'SIN_ESTADO', 1, null, 100);
INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, NIVEL_APRENDIZAJE, PP_MAX, TIPO_MOV, POTENCIA, TIPO, ESTADO, TURNOS, MEJORA, PROBABILIDAD) VALUES (59, 'RUGIDO', 3, 40, 'NORMAL', null, 'MEJORA', 'SIN_ESTADO', 1, 'BAJAR_ATAQUE', 100);

/* INSERTS TABLA OBJETO */
INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO) VALUES (1, 'Pesa', 1.20, null, 1.20, null, 0.80, 350);
INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO) VALUES (2, 'Pluma', null, null, 0.80, 0.80, 1.30, 400);
INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO) VALUES (3, 'Chaleco', 0.85, null, 1.20, 1.20, 0.85, 250);
INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO) VALUES (4, 'Baston', null, null, null, null, null, 300);
INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO) VALUES (5, 'Pilas', null, null, null, null, null, 500);
INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO) VALUES (6, 'Eter', null, null, null, null, null, 100);
INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO) VALUES (7, 'Anillo unico', 10, null, null, null, null, 6666);
INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO) VALUES (8, 'Pokeball', null, null, null, null, null, 50);
INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO) VALUES (9, 'Superball', null, null, null, null, null, 150);
INSERT INTO OBJETO (ID_OBJETO, NOM_OBJETO, ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, PRECIO) VALUES (10, 'Ultraball', null, null, null, null, null, 250);

/*INSERTS LUISRE*/
INSERT INTO RIVAL (ID_RIVAL, NOMBRE, FRASE_VICTORIA, FRASE_DERROTA, FRASE_RENDICION) VALUES (5, "Luisre", "Mmmmh... Parece que algo si has aprendido durante el curso eh. Bueno espero que sigas asi. Aqui tienes la matricula y no te relajes Antonio puede ser un rival duro. ", "Hice todo lo que pude pero finalmente tendre que ponerle la matricula a Adriano.", "Entiendo que vas a hacer el examen, no? Ya te avise que ChatGPT no te haria el proyecto pokemon.");

INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(1 ,6 ,"Charizard" , 297, 297 ,204 ,254, 192 ,206 ,236 ,100 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 5);
INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(2 ,130 ,"Gyarados" ,336 ,336 ,286, 156 ,194 ,236 ,198 ,100 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 5);
INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(3 ,65 ,"Alakazam" ,251 ,251 ,136, 306 ,126 ,226 ,276 ,100 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 5);
INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(4 ,149 ,"Dragonite" ,332 ,332 ,304, 236 ,226 ,236 ,196 ,100 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 5);
INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(5 ,94 ,"Gengar" ,261 ,261 ,166, 296 ,156 ,186 ,256 ,100 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 5);
INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(6 ,153 ,"Balrog" ,401, 401, 256, 376, 256, 316, 226,100 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 5);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (1, 19, 15);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (1, 18, 25);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (1, 48, 5);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (1, 57, 15);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (2, 54, 35);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (2, 51, 5);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (2, 2, 15);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (2, 3, 5);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (3, 35, 20);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (3, 37, 15);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (3, 59, 40);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (3, 55, 5);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (4, 9, 10);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (4, 49, 35);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (4, 51, 5);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (4, 58, 40);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (5, 44, 30);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (5, 47, 35);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (5, 15, 30);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (5, 16, 20);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (6, 21, 15);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (6, 19, 5);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (6, 37, 15);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (6, 56, 30);

/*INSERTS CARLOS*/
INSERT INTO RIVAL (ID_RIVAL, NOMBRE, FRASE_VICTORIA, FRASE_DERROTA, FRASE_RENDICION) VALUES (4, "Carlos", "Guauu! no sabía que eras tan bueno, Tendré que irme a surfear y seguir mejorando.", "Sabía que no serías capaz de coger esta ola.", "¿Todavía no te has metido al agua y ya tienes miedo ?");

INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(7 ,42 ,"Golbat" , 291, 291, 196, 166, 176, 186, 216 ,80 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 4);
INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(8 ,94 ,"Gengar" ,261 ,261 ,166, 296 ,156 ,186 ,256, 80 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 4);
INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(9 ,34 ,"Nidoking" ,303, 303, 240, 206, 190, 186, 206, 80 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 4);
INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(10 ,131 ,"Lapras" , 401, 401, 206, 206, 196, 226, 156, 80 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 4);
INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(11 ,162 ,"Druddigon" ,260, 260, 244, 148, 196, 196, 129, 80 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 4);
INSERT INTO POKEMON(ID_POKEMON, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD, NIVEL, FERTILIDAD, SEXO, ESTADO, EQUIPO, TIPO_PROPIETARIO, ID_RIVAL) VALUES(12 ,152 ,"Mewtwo Surfero" , 307, 307, 180, 260, 298, 196, 260, 80 ,0 ,'M' , 'SIN_ESTADO', 1, "RIVAL", 4);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (7, 44, 30);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (7, 52, 35);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (8, 47, 35);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (8, 15, 30);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (9, 41, 5);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (9, 44, 30);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (10, 24, 10);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (10, 3, 5);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (11, 9, 10);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (11, 15, 30);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (12, 2, 15);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (12, 3, 5);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (12, 37, 15);
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES (12, 34, 30);

/*pokemon y movimientos de Diego*/
INSERT INTO RIVAL (ID_RIVAL, NOMBRE, FRASE_VICTORIA, FRASE_DERROTA, FRASE_RENDICION) VALUES (2, "Diego", "Ale! Por gracioso acabo de subir 70 ejercicios mas de linux.", "La respuesta estaba en el man.", "sudo apt intall vuelveCobarde!");

INSERT INTO POKEMON
  (ID_POKEMON, ID_RIVAL, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,
   ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD,
   NIVEL, SEXO, ESTADO, TIPO_PROPIETARIO, EXPERIENCIA)
VALUES
  (19, 2, 158, 'vMon', 125, 125, 82, 82, 78, 78, 91, 40, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (20, 2, 159, 'warGreymon', 169, 169, 132, 132, 116, 116, 108, 40, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (21, 2, 157, 'Skullgreyd', 161, 161, 156, 84, 108, 108, 140, 40, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (22, 2, 156, 'dReaper', 153, 153, 84, 156, 92, 92, 124, 40, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (23, 2, 161, 'piedMon', 141, 141, 100, 164, 100, 100, 140, 40, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (24, 2, 160, 'Ultimate WarGreymon', 137, 137, 156, 156, 100, 100, 156, 40, 'X', 'SIN_ESTADO', 'RIVAL', 0);
  
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (19, 1, 30),
  (19, 2, 15),
  (19, 3,  5), 
  (19, 4, 10); 

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (20,  9, 10), 
  (20, 10, 30), 
  (20, 12, 15),
  (20, 13, 10);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (21, 15, 30),  
  (21,  9, 10),
  (21, 56, 30), 
  (21, 50, 35); 

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (22, 37, 15),
  (22, 36, 30),
  (22, 35, 20),
  (22, 50, 35); 

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (23, 17, 10), 
  (23, 15, 30), 
  (23, 26, 25),
  (23, 27, 30);  

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (24,  9, 10),  
  (24, 10, 30),
  (24, 13, 10), 
  (24, 14, 10);
  
/*pokemon y movimientos de Carrion*/
INSERT INTO RIVAL (ID_RIVAL, NOMBRE, FRASE_VICTORIA, FRASE_DERROTA, FRASE_RENDICION) VALUES (1, "Carrion", "Me habras vencido a mi pero no tienes nada que hacer contra el jefe de departamento", "Estas despedido!", "Con este curriculum no vas a llegar a ninguna parte");

INSERT INTO POKEMON
  (ID_POKEMON, ID_RIVAL, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,
   ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD,
   NIVEL, SEXO, ESTADO, TIPO_PROPIETARIO, EXPERIENCIA)
VALUES
  (25, 1, 24, 'Arbok', 85, 85, 74, 62, 63, 67, 68, 20, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (26, 1, 26, 'Raichu', 85, 85, 72, 72, 58, 68, 80, 20, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (27, 1, 31, 'Nidoqueen', 97, 97, 72, 66, 70, 70, 66, 20, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (28, 1, 55, 'Golduck', 93, 93, 68, 74, 67, 68, 70, 20, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (29, 1, 68, 'Machamp', 97, 97, 88, 62, 68, 70, 58, 20, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (30, 1, 154, 'Carrinchear', 109, 109, 80, 60, 72, 72, 66, 20, 'X', 'SIN_ESTADO', 'RIVAL', 0);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (25, 48, 15),
  (25, 49, 20),
  (25, 47, 15),
  (25, 50, 35);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (26, 10, 30),
  (26, 12, 15),
  (26, 13, 10),
  (26, 14, 10);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (27, 30, 30),
  (27, 32, 10),
  (27, 50, 35),
  (27, 36, 30);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (28, 1, 30),
  (28, 2, 15),
  (28, 3, 5),
  (28, 50, 35);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (29, 26, 25),
  (29, 27, 30),
  (29, 50, 35),
  (29, 17, 10);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (30, 26, 25),
  (30, 49, 20),
  (30, 50, 35),
  (30, 13, 10);
  
/*pokemon y movimientos de Fernando*/
INSERT INTO RIVAL (ID_RIVAL, NOMBRE, FRASE_VICTORIA, FRASE_DERROTA, FRASE_RENDICION) VALUES (3, "Fernando", "Habras ganado, pero en BaseX gane yo", "Has llegado tarde. Esperate hasta la siguiente hora.", "Vete si quieres pero te tengo que poner falta.");

INSERT INTO POKEMON
  (ID_POKEMON, ID_RIVAL, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,
   ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD,
   NIVEL, SEXO, ESTADO, TIPO_PROPIETARIO, EXPERIENCIA)
VALUES
  (13, 3, 143, 'Snorlax', 293, 293, 168, 114, 114, 168, 72, 60, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (14, 3, 18,  'Pidgeot', 200, 200, 132, 126, 120, 120, 157, 60, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (15, 3, 144, 'Articuno', 209, 209, 138, 156, 150, 186, 138, 60, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (16, 3, 145, 'Zapdos',   209, 209, 144, 138, 186, 144, 156, 60, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (17, 3, 146, 'Moltres',  209, 209, 156, 144, 186, 138, 144, 60, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (18, 3, 155, 'Xaturnino',191, 191, 138, 162, 132, 132, 162, 60, 'X', 'SIN_ESTADO', 'RIVAL', 0);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (13, 54, 35),
  (13, 55,  5),
  (13, 56, 30),
  (13, 50, 35);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (14, 48,  5),
  (14, 52, 35),
  (14, 53, 15),
  (14, 56, 30);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (15, 24, 10),
  (15, 25,  5),
  (15, 48,  5),
  (15, 53, 15);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (16, 10, 30),
  (16, 13, 10),
  (16, 49, 35),
  (16, 53, 15);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (17, 19, 15),
  (17, 20,  5),
  (17, 48,  5),
  (17, 53, 15);

INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (18, 37, 15),
  (18, 51,  5),
  (18, 52, 35),
  (18, 50, 35);

/* Pokémon de Juanan y Victoria */
INSERT INTO RIVAL (ID_RIVAL, NOMBRE, FRASE_VICTORIA, FRASE_DERROTA, FRASE_RENDICION) VALUES (6, "Juanan y Victoria", "Mejor hagamos como que esto no ha pasado, ¿vale?", "Esto te pasa por no entrar en animaciones.", "Más te vale estar yendo a matricularte en animaciones.");

INSERT INTO POKEMON
  (ID_POKEMON, ID_RIVAL, NUM_POKEDEX, MOTE, VITALIDAD_MAX, VITALIDAD_ACT,
   ATAQUE, AT_ESPECIAL, DEFENSA, DEF_ESPECIAL, VELOCIDAD,
   NIVEL, SEXO, ESTADO, TIPO_PROPIETARIO, EXPERIENCIA)
VALUES
  (31, 6, 166, 'Nintales Alola', 287, 287, 170, 196, 186, 236, 240, -1, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (32, 6, 152, 'Mewtwo Surfero', 353, 353, 365, 435, 389, 471, 365, -1, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (33, 6, 153, 'Balrog',         357, 357, 335, 335, 410, 410, 275, -1, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (34, 6, 154, 'Carrinchear',    341, 341, 311, 223, 355, 355, 254, -1, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (35, 6, 155, 'Xaturnino',      361, 361, 325, 405, 331, 331, 415, -1, 'X', 'SIN_ESTADO', 'RIVAL', 0),
  (36, 6, 160, 'Ultimate WarGreymon', 377, 377, 451, 451, 331, 331, 451, -1, 'X', 'SIN_ESTADO', 'RIVAL', 0);

/* Movimientos de Nintales Alola */
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (31, 22, 15), 
  (31, 24, 10),
  (31, 25,  5),
  (31, 56, 30);

/* Movimientos de Mewtwo Surfero */
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (32,  2, 15),
  (32,  3,  5),
  (32, 54, 35),
  (32, 51,  5);

/* Movimientos de Balrog */
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (33, 19, 15),
  (33, 20,  5),
  (33, 48,  5),
  (33, 53, 15);

/* Movimientos de Carrinchear */
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (34, 26, 25),
  (34, 27, 30),
  (34, 50, 35),
  (34, 17, 10);

/* Movimientos de Xaturnino */
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (35, 37, 15),
  (35, 51,  5),
  (35, 52, 35),
  (35, 50, 35);

/* Movimientos de Ultimate WarGreymon */
INSERT INTO MOVIMIENTO_POKEMON (ID_POKEMON, ID_MOVIMIENTO, PP_ACTUALES) VALUES
  (36,  9, 10),
  (36, 10, 30),
  (36, 13, 10),
  (36, 14, 10);